// Generated by AI

#include "io/CsvReader.h"
#include "io/CsvTokenizer.h"

#include <catch.hpp>
#include <filesystem>
#include <fstream>
#include <string>

namespace fs = std::filesystem;

namespace {

class CreateTempCsvFile {
public:
    CreateTempCsvFile(const std::string& content, const std::string& filename) {
        path_ = "/tmp/" + filename;
        std::ofstream out(path_);
        out << content;
        out.close();
    }

    ~CreateTempCsvFile() {
        fs::remove(path_);
    }

    std::string path() const {
        return path_.string();
    }

private:
    fs::path path_;
};

}  // namespace

TEST_CASE("Simple Csv reading", "[CsvReader]") {
    CreateTempCsvFile tempFile("INT32:h1,INT32:h2\n1,2", "test_reader_simple.csv");
    CsvReader reader(tempFile.path());

    VectorOfStrings header_names;
    std::vector<ColumnType> header_types;
    reader.ReadHeader(header_names, header_types);
    REQUIRE(header_names.Size() == 2);
    REQUIRE(header_names.GetString(0) == std::string_view("h1"));
    REQUIRE(header_names.GetString(1) == std::string_view("h2"));
    REQUIRE(header_types[0] == ColumnType::INT32);

    VectorOfStrings2D row;
    REQUIRE(reader.ReadRow(row));
    REQUIRE(row.ColumnsInCurrentLine() == 2);
    REQUIRE(row.GetString(0) == std::string_view("1"));
    REQUIRE(row.GetString(1) == std::string_view("2"));

    row.StartNewLine(); // Emulate how batching works
    REQUIRE_FALSE(reader.ReadRow(row));
}

TEST_CASE("CsvTokenizer does not materialize empty token on hard EOF", "[CsvTokenizer]") {
    CreateTempCsvFile tempFile("", "test_tokenizer_hard_eof.csv");
    CsvTokenizer tokenizer(tempFile.path());
    VectorOfStrings2D row;

    const size_t width_before = row.Width();
    tokenizer.GetNextRow(row);

    REQUIRE(row.Width() == width_before);
    REQUIRE(tokenizer.IsEOF());
}

TEST_CASE("CsvTokenizer keeps last token without trailing newline", "[CsvTokenizer]") {
    CreateTempCsvFile tempFile("a,b", "test_tokenizer_no_trailing_newline.csv");
    CsvTokenizer tokenizer(tempFile.path());
    VectorOfStrings2D row;

    tokenizer.GetNextRow(row);
    row.StartNewLine();
    tokenizer.GetNextRow(row);

    REQUIRE(row.Width() == 2);
    REQUIRE(row.GetString(0) == std::string_view("a"));
    REQUIRE(row.GetString(1) == std::string_view("b"));
    REQUIRE(tokenizer.IsEOF());
}

TEST_CASE("CsvReader does not return fake empty row at EOF", "[CsvReader]") {
    CreateTempCsvFile tempFile("INT32:h1,INT32:h2\n1,2", "test_reader_eof.csv");
    CsvReader reader(tempFile.path());

    VectorOfStrings header_names;
    std::vector<ColumnType> header_types;
    reader.ReadHeader(header_names, header_types);
    REQUIRE(header_names.Size() == 2);

    VectorOfStrings2D row;
    REQUIRE(reader.ReadRow(row));
    REQUIRE(row.ColumnsInCurrentLine() == 2);
    REQUIRE(row.GetString(0) == std::string_view("1"));
    REQUIRE(row.GetString(1) == std::string_view("2"));
    row.StartNewLine();

    REQUIRE_FALSE(reader.ReadRow(row));
    REQUIRE(row.ColumnsInCurrentLine() == 0);
}

TEST_CASE("CsvReader does not add extra row for trailing newline", "[CsvReader]") {
    CreateTempCsvFile tempFile("INT32:h1\nx\n", "test_reader_trailing_newline.csv");
    CsvReader reader(tempFile.path());

    VectorOfStrings header_names;
    std::vector<ColumnType> header_types;
    reader.ReadHeader(header_names, header_types);

    VectorOfStrings2D row;
    REQUIRE(reader.ReadRow(row));
    REQUIRE(row.ColumnsInCurrentLine() == 1);
    REQUIRE(row.GetString(0) == std::string_view("x"));
    row.StartNewLine();
    REQUIRE_FALSE(reader.ReadRow(row));
}

TEST_CASE("CsvReader preserves empty fields", "[CsvReader]") {
    CreateTempCsvFile tempFile("STRING:a,STRING:b\n,\n", "test_reader_empty_fields.csv");
    CsvReader reader(tempFile.path());

    VectorOfStrings header_names;
    std::vector<ColumnType> header_types;
    reader.ReadHeader(header_names, header_types);

    VectorOfStrings2D row;
    REQUIRE(reader.ReadRow(row));
    REQUIRE(row.ColumnsInCurrentLine() == 2);
    REQUIRE(row.GetString(0) == std::string_view(""));
    REQUIRE(row.GetString(1) == std::string_view(""));
    row.StartNewLine();
    REQUIRE_FALSE(reader.ReadRow(row));
}
