// Generated by AI

#include "io/CsvToColumnar.h"
#include "io/ColumnarReader.h"
#include "types/ColumnType.h"

#include <catch.hpp>
#include <fstream>
#include <filesystem>

namespace fs = std::filesystem;

std::string CreateTempCSVFile(const std::string& content,
                              const std::string& filename = "test_rw.csv") {
    std::string filepath = "/tmp/" + filename;
    std::ofstream file(filepath);
    file << content;
    file.close();
    return filepath;
}

void RemoveTempFile(const std::string& filepath) {
    if (fs::exists(filepath)) {
        fs::remove(filepath);
    }
}

TEST_CASE("CsvToColumnar: Basic write operation", "[CsvToColumnar]") {
    std::string csv_content =
        "INT32:id,STRING:name\n"
        "1,Alice\n"
        "2,Bob\n"
        "3,Charlie\n";
    std::string csv_path = CreateTempCSVFile(csv_content, "test_CsvToColumnar_basic.csv");
    std::string output_path = "/tmp/test_CsvToColumnar_basic.bin";

    SECTION("Write CSV to binary format") {
        REQUIRE_NOTHROW(CsvToColumnar::Convert(csv_path, output_path));
        REQUIRE(fs::exists(output_path));

        std::ifstream file(output_path, std::ios::binary);
        file.seekg(0, std::ios::end);
        size_t file_size = file.tellg();
        REQUIRE(file_size > 0);

        file.seekg(0, std::ios::beg);
        char magic[5] = {0};
        file.read(magic, 4);
        REQUIRE(std::string(magic) == "TUFF");

        file.close();
    }

    RemoveTempFile(csv_path);
    RemoveTempFile(output_path);
}

TEST_CASE("CsvToColumnar: Multiple types", "[CsvToColumnar]") {
    std::string csv_content =
        "INT32:id,STRING:name,FLOAT:score\n"
        "1,Alice,95.5\n"
        "2,Bob,87.3\n";
    std::string csv_path = CreateTempCSVFile(csv_content, "test_CsvToColumnar_multi.csv");
    std::string output_path = "/tmp/test_CsvToColumnar_multi.bin";

    CsvToColumnar::Convert(csv_path, output_path);

    REQUIRE(fs::exists(output_path));
    REQUIRE(fs::file_size(output_path) > 0);

    RemoveTempFile(csv_path);
    RemoveTempFile(output_path);
}

TEST_CASE("Reader: Read metadata", "[Reader]") {
    std::string csv_content =
        "INT32:id,STRING:name\n"
        "1,Alice\n"
        "2,Bob\n";
    std::string csv_path = CreateTempCSVFile(csv_content, "test_reader_meta.csv");
    std::string output_path = "/tmp/test_reader_meta.bin";

    CsvToColumnar::Convert(csv_path, output_path);

    SECTION("Read and verify metadata") {
        ColumnarReader reader(output_path);
        const auto& metadata = reader.GetMetadata();

        REQUIRE(metadata.size() == 2);
        REQUIRE(metadata[0].name == "id");
        REQUIRE(metadata[0].type == ColumnType::INT32);
        REQUIRE(metadata[1].name == "name");
        REQUIRE(metadata[1].type == ColumnType::STRING);
    }

    RemoveTempFile(csv_path);
    RemoveTempFile(output_path);
}

TEST_CASE("Reader: Read typed column data", "[Reader]") {
    std::string csv_content =
        "INT32:id,STRING:city\n"
        "1,Moscow\n"
        "2,London\n";
    std::string csv_path = CreateTempCSVFile(csv_content, "test_reader_typed.csv");
    std::string output_path = "/tmp/test_reader_typed.bin";

    CsvToColumnar::Convert(csv_path, output_path);

    ColumnarReader reader(output_path);

    SECTION("Read INT32 column") {
        auto column = reader.GetColumnData(0, 0);
        REQUIRE(column != nullptr);
        REQUIRE(column->GetType() == ColumnType::INT32);
        REQUIRE(column->Size() == 2);
    }

    SECTION("Read STRING column") {
        auto column = reader.GetColumnData(1, 0);
        REQUIRE(column != nullptr);
        REQUIRE(column->GetType() == ColumnType::STRING);
        REQUIRE(column->Size() == 2);
    }

    RemoveTempFile(csv_path);
    RemoveTempFile(output_path);
}
