//
// Created by ragnarokk on 04.01.2026.
//

// Generated by AI

#include <catch.hpp>

#include "CSVReader.h"
#include "CSVTokenizer.h"

#include <filesystem>
#include <fstream>
#include <string>

namespace fs = std::filesystem;

namespace {

std::string CreateTempCSVFile(const std::string& content, const std::string& filename) {
    const std::string path = "/tmp/" + filename;
    std::ofstream out(path);
    out << content;
    out.close();
    return path;
}

}  // namespace

TEST_CASE("CSVTokenizer does not materialize empty token on hard EOF", "[CSVTokenizer]") {
    const std::string path = CreateTempCSVFile("", "test_tokenizer_hard_eof.csv");
    CSVTokenizer tokenizer(path);
    VectorOfStrings2D row;

    const size_t width_before = row.Width();
    tokenizer.GetNextRow(row);

    REQUIRE(row.Width() == width_before);
    REQUIRE(tokenizer.IsEOF());

    fs::remove(path);
}

TEST_CASE("CSVTokenizer keeps last token without trailing newline", "[CSVTokenizer]") {
    const std::string path = CreateTempCSVFile("a,b", "test_tokenizer_no_trailing_newline.csv");
    CSVTokenizer tokenizer(path);
    VectorOfStrings2D row;

    tokenizer.GetNextRow(row);
    tokenizer.GetNextRow(row);

    REQUIRE(row.Width() == 2);
    REQUIRE(row.GetString(0) == std::string_view("a"));
    REQUIRE(row.GetString(1) == std::string_view("b"));
    REQUIRE(tokenizer.IsEOF());

    fs::remove(path);
}

TEST_CASE("CSVReader does not return fake empty row at EOF", "[CSVReader]") {
    const std::string path = CreateTempCSVFile("h1,h2\n1,2", "test_reader_eof.csv");
    CSVReader reader(path);

    VectorOfStrings2D header;
    reader.ReadHeader(header);
    REQUIRE(header.Width() == 2);

    VectorOfStrings2D row;
    REQUIRE(reader.ReadRow(row));
    REQUIRE(row.Width() == 2);
    REQUIRE(row.GetString(0) == std::string_view("1"));
    REQUIRE(row.GetString(1) == std::string_view("2"));

    REQUIRE_FALSE(reader.ReadRow(row));
    REQUIRE(row.Width() == 0);

    fs::remove(path);
}

TEST_CASE("CSVReader does not add extra row for trailing newline", "[CSVReader]") {
    const std::string path = CreateTempCSVFile("h1\nx\n", "test_reader_trailing_newline.csv");
    CSVReader reader(path);

    VectorOfStrings2D header;
    reader.ReadHeader(header);

    VectorOfStrings2D row;
    REQUIRE(reader.ReadRow(row));
    REQUIRE(row.Width() == 1);
    REQUIRE(row.GetString(0) == std::string_view("x"));
    REQUIRE_FALSE(reader.ReadRow(row));

    fs::remove(path);
}

TEST_CASE("CSVReader preserves empty fields", "[CSVReader]") {
    const std::string path = CreateTempCSVFile("a,b\n,\n", "test_reader_empty_fields.csv");
    CSVReader reader(path);

    VectorOfStrings2D header;
    reader.ReadHeader(header);

    VectorOfStrings2D row;
    REQUIRE(reader.ReadRow(row));
    REQUIRE(row.Width() == 2);
    REQUIRE(row.GetString(0) == std::string_view(""));
    REQUIRE(row.GetString(1) == std::string_view(""));
    REQUIRE_FALSE(reader.ReadRow(row));

    fs::remove(path);
}
